######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 17 00:36:41 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CardDeck.h CardHand.h
SOURCES += CardDeck.cpp CardHand.cpp main.cpp
